export PIPELINE_ROOT=~/epihiper-setup-logs/2023-12-05/
export CONTROLLER_TASK_TIMEOUT="5000000"
export CONTROLLER_CONTROLLER_PORT=18001
export CONTROLLER_CERT_FILE="$PIPELINE_ROOT/common.crt"
export CONTROLLER_KEY_FILE="$PIPELINE_ROOT/common.key"
export CONTROLLER_SETUP_ROOT="$PIPELINE_ROOT/controller_setup_root"
export CONTROLLER_CONTROLLER_HOST=0.0.0.0
